# Generated by Django 4.0.1 on 2022-01-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('temp', models.IntegerField(default=0)),
                ('kind', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('c_pic', models.CharField(max_length=200)),
            ],
        ),
    ]
