# Generated by Django 4.0.1 on 2022-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
