# Generated by Django 4.0.1 on 2022-01-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.CharField(default='ootdBasic.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='pw',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
