# Generated by Django 4.0.1 on 2022-01-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_id_member_mem_id_rename_name_member_nick_and_more'),
        ('member', '0004_alter_member_birth_alter_member_email_and_more'),
    ]

    operations = [
    ]
